// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Constants.proto

package com.orange.protocol.message;

public final class ConstantsProtos {
  private ConstantsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code barrage.PBDeviceType}
   */
  public enum PBDeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEVICE_TYPE_IPHONE = 1;</code>
     */
    DEVICE_TYPE_IPHONE(0, 1),
    /**
     * <code>DEVICE_TYPE_ANDROID = 2;</code>
     */
    DEVICE_TYPE_ANDROID(1, 2),
    /**
     * <code>DEVICE_TYPE_WINDOW = 3;</code>
     */
    DEVICE_TYPE_WINDOW(2, 3),
    ;

    /**
     * <code>DEVICE_TYPE_IPHONE = 1;</code>
     */
    public static final int DEVICE_TYPE_IPHONE_VALUE = 1;
    /**
     * <code>DEVICE_TYPE_ANDROID = 2;</code>
     */
    public static final int DEVICE_TYPE_ANDROID_VALUE = 2;
    /**
     * <code>DEVICE_TYPE_WINDOW = 3;</code>
     */
    public static final int DEVICE_TYPE_WINDOW_VALUE = 3;


    public final int getNumber() { return value; }

    public static PBDeviceType valueOf(int value) {
      switch (value) {
        case 1: return DEVICE_TYPE_IPHONE;
        case 2: return DEVICE_TYPE_ANDROID;
        case 3: return DEVICE_TYPE_WINDOW;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PBDeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PBDeviceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBDeviceType>() {
            public PBDeviceType findValueByNumber(int number) {
              return PBDeviceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.orange.protocol.message.ConstantsProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final PBDeviceType[] VALUES = values();

    public static PBDeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PBDeviceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:barrage.PBDeviceType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Constants.proto\022\007barrage*W\n\014PBDeviceTy" +
      "pe\022\026\n\022DEVICE_TYPE_IPHONE\020\001\022\027\n\023DEVICE_TYP" +
      "E_ANDROID\020\002\022\026\n\022DEVICE_TYPE_WINDOW\020\003B.\n\033c" +
      "om.orange.protocol.messageB\017ConstantsPro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
