// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Error.proto

package com.orange.protocol.message;

public final class ErrorProtos {
  private ErrorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code barrage.PBError}
   */
  public enum PBError
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR_READ_POST_DATA = 1000001;</code>
     */
    ERROR_READ_POST_DATA(0, 1000001),
    /**
     * <code>ERROR_PARSE_POST_DATA = 1000002;</code>
     */
    ERROR_PARSE_POST_DATA(1, 1000002),
    ;

    /**
     * <code>ERROR_READ_POST_DATA = 1000001;</code>
     */
    public static final int ERROR_READ_POST_DATA_VALUE = 1000001;
    /**
     * <code>ERROR_PARSE_POST_DATA = 1000002;</code>
     */
    public static final int ERROR_PARSE_POST_DATA_VALUE = 1000002;


    public final int getNumber() { return value; }

    public static PBError valueOf(int value) {
      switch (value) {
        case 1000001: return ERROR_READ_POST_DATA;
        case 1000002: return ERROR_PARSE_POST_DATA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PBError>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PBError>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBError>() {
            public PBError findValueByNumber(int number) {
              return PBError.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.orange.protocol.message.ErrorProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final PBError[] VALUES = values();

    public static PBError valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PBError(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:barrage.PBError)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Error.proto\022\007barrage*B\n\007PBError\022\032\n\024ERR" +
      "OR_READ_POST_DATA\020\301\204=\022\033\n\025ERROR_PARSE_POS" +
      "T_DATA\020\302\204=B*\n\033com.orange.protocol.messag" +
      "eB\013ErrorProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
