// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.orange.protocol.message;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:barrage.PBDataRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>optional int32 requestId = 2;</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional int32 requestId = 2;</code>
     */
    int getRequestId();

    /**
     * <code>optional int32 version = 3;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 3;</code>
     */
    int getVersion();

    /**
     * <code>optional .barrage.PBDevice device = 30;</code>
     */
    boolean hasDevice();
    /**
     * <code>optional .barrage.PBDevice device = 30;</code>
     */
    com.orange.protocol.message.CommonProtos.PBDevice getDevice();
    /**
     * <code>optional .barrage.PBDevice device = 30;</code>
     */
    com.orange.protocol.message.CommonProtos.PBDeviceOrBuilder getDeviceOrBuilder();

    /**
     * <code>optional string countryCode = 31;</code>
     */
    boolean hasCountryCode();
    /**
     * <code>optional string countryCode = 31;</code>
     */
    java.lang.String getCountryCode();
    /**
     * <code>optional string countryCode = 31;</code>
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();

    /**
     * <code>optional string languageCode = 32;</code>
     */
    boolean hasLanguageCode();
    /**
     * <code>optional string languageCode = 32;</code>
     */
    java.lang.String getLanguageCode();
    /**
     * <code>optional string languageCode = 32;</code>
     */
    com.google.protobuf.ByteString
        getLanguageCodeBytes();
  }
  /**
   * Protobuf type {@code barrage.PBDataRequest}
   */
  public static final class PBDataRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:barrage.PBDataRequest)
      PBDataRequestOrBuilder {
    // Use PBDataRequest.newBuilder() to construct.
    private PBDataRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBDataRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBDataRequest defaultInstance;
    public static PBDataRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PBDataRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBDataRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              requestId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt32();
              break;
            }
            case 242: {
              com.orange.protocol.message.CommonProtos.PBDevice.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = device_.toBuilder();
              }
              device_ = input.readMessage(com.orange.protocol.message.CommonProtos.PBDevice.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(device_);
                device_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 250: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              countryCode_ = bs;
              break;
            }
            case 258: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              languageCode_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orange.protocol.message.MessageProtos.PBDataRequest.class, com.orange.protocol.message.MessageProtos.PBDataRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PBDataRequest> PARSER =
        new com.google.protobuf.AbstractParser<PBDataRequest>() {
      public PBDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBDataRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBDataRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int REQUESTID_FIELD_NUMBER = 2;
    private int requestId_;
    /**
     * <code>optional int32 requestId = 2;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 requestId = 2;</code>
     */
    public int getRequestId() {
      return requestId_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>optional int32 version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int DEVICE_FIELD_NUMBER = 30;
    private com.orange.protocol.message.CommonProtos.PBDevice device_;
    /**
     * <code>optional .barrage.PBDevice device = 30;</code>
     */
    public boolean hasDevice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .barrage.PBDevice device = 30;</code>
     */
    public com.orange.protocol.message.CommonProtos.PBDevice getDevice() {
      return device_;
    }
    /**
     * <code>optional .barrage.PBDevice device = 30;</code>
     */
    public com.orange.protocol.message.CommonProtos.PBDeviceOrBuilder getDeviceOrBuilder() {
      return device_;
    }

    public static final int COUNTRYCODE_FIELD_NUMBER = 31;
    private java.lang.Object countryCode_;
    /**
     * <code>optional string countryCode = 31;</code>
     */
    public boolean hasCountryCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string countryCode = 31;</code>
     */
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          countryCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string countryCode = 31;</code>
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGECODE_FIELD_NUMBER = 32;
    private java.lang.Object languageCode_;
    /**
     * <code>optional string languageCode = 32;</code>
     */
    public boolean hasLanguageCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string languageCode = 32;</code>
     */
    public java.lang.String getLanguageCode() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          languageCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string languageCode = 32;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageCodeBytes() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = 0;
      requestId_ = 0;
      version_ = 0;
      device_ = com.orange.protocol.message.CommonProtos.PBDevice.getDefaultInstance();
      countryCode_ = "";
      languageCode_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasDevice()) {
        if (!getDevice().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, requestId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(30, device_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(31, getCountryCodeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(32, getLanguageCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, requestId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(30, device_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(31, getCountryCodeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(32, getLanguageCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.protocol.message.MessageProtos.PBDataRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code barrage.PBDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:barrage.PBDataRequest)
        com.orange.protocol.message.MessageProtos.PBDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orange.protocol.message.MessageProtos.PBDataRequest.class, com.orange.protocol.message.MessageProtos.PBDataRequest.Builder.class);
      }

      // Construct using com.orange.protocol.message.MessageProtos.PBDataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (deviceBuilder_ == null) {
          device_ = com.orange.protocol.message.CommonProtos.PBDevice.getDefaultInstance();
        } else {
          deviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        countryCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        languageCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataRequest_descriptor;
      }

      public com.orange.protocol.message.MessageProtos.PBDataRequest getDefaultInstanceForType() {
        return com.orange.protocol.message.MessageProtos.PBDataRequest.getDefaultInstance();
      }

      public com.orange.protocol.message.MessageProtos.PBDataRequest build() {
        com.orange.protocol.message.MessageProtos.PBDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orange.protocol.message.MessageProtos.PBDataRequest buildPartial() {
        com.orange.protocol.message.MessageProtos.PBDataRequest result = new com.orange.protocol.message.MessageProtos.PBDataRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (deviceBuilder_ == null) {
          result.device_ = device_;
        } else {
          result.device_ = deviceBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.countryCode_ = countryCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.languageCode_ = languageCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.protocol.message.MessageProtos.PBDataRequest) {
          return mergeFrom((com.orange.protocol.message.MessageProtos.PBDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orange.protocol.message.MessageProtos.PBDataRequest other) {
        if (other == com.orange.protocol.message.MessageProtos.PBDataRequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasDevice()) {
          mergeDevice(other.getDevice());
        }
        if (other.hasCountryCode()) {
          bitField0_ |= 0x00000010;
          countryCode_ = other.countryCode_;
          onChanged();
        }
        if (other.hasLanguageCode()) {
          bitField0_ |= 0x00000020;
          languageCode_ = other.languageCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasDevice()) {
          if (!getDevice().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orange.protocol.message.MessageProtos.PBDataRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orange.protocol.message.MessageProtos.PBDataRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int requestId_ ;
      /**
       * <code>optional int32 requestId = 2;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 requestId = 2;</code>
       */
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <code>optional int32 requestId = 2;</code>
       */
      public Builder setRequestId(int value) {
        bitField0_ |= 0x00000002;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 requestId = 2;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>optional int32 version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 3;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 3;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        onChanged();
        return this;
      }

      private com.orange.protocol.message.CommonProtos.PBDevice device_ = com.orange.protocol.message.CommonProtos.PBDevice.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.protocol.message.CommonProtos.PBDevice, com.orange.protocol.message.CommonProtos.PBDevice.Builder, com.orange.protocol.message.CommonProtos.PBDeviceOrBuilder> deviceBuilder_;
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      public boolean hasDevice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      public com.orange.protocol.message.CommonProtos.PBDevice getDevice() {
        if (deviceBuilder_ == null) {
          return device_;
        } else {
          return deviceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      public Builder setDevice(com.orange.protocol.message.CommonProtos.PBDevice value) {
        if (deviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          device_ = value;
          onChanged();
        } else {
          deviceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      public Builder setDevice(
          com.orange.protocol.message.CommonProtos.PBDevice.Builder builderForValue) {
        if (deviceBuilder_ == null) {
          device_ = builderForValue.build();
          onChanged();
        } else {
          deviceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      public Builder mergeDevice(com.orange.protocol.message.CommonProtos.PBDevice value) {
        if (deviceBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              device_ != com.orange.protocol.message.CommonProtos.PBDevice.getDefaultInstance()) {
            device_ =
              com.orange.protocol.message.CommonProtos.PBDevice.newBuilder(device_).mergeFrom(value).buildPartial();
          } else {
            device_ = value;
          }
          onChanged();
        } else {
          deviceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      public Builder clearDevice() {
        if (deviceBuilder_ == null) {
          device_ = com.orange.protocol.message.CommonProtos.PBDevice.getDefaultInstance();
          onChanged();
        } else {
          deviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      public com.orange.protocol.message.CommonProtos.PBDevice.Builder getDeviceBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDeviceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      public com.orange.protocol.message.CommonProtos.PBDeviceOrBuilder getDeviceOrBuilder() {
        if (deviceBuilder_ != null) {
          return deviceBuilder_.getMessageOrBuilder();
        } else {
          return device_;
        }
      }
      /**
       * <code>optional .barrage.PBDevice device = 30;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.protocol.message.CommonProtos.PBDevice, com.orange.protocol.message.CommonProtos.PBDevice.Builder, com.orange.protocol.message.CommonProtos.PBDeviceOrBuilder> 
          getDeviceFieldBuilder() {
        if (deviceBuilder_ == null) {
          deviceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.orange.protocol.message.CommonProtos.PBDevice, com.orange.protocol.message.CommonProtos.PBDevice.Builder, com.orange.protocol.message.CommonProtos.PBDeviceOrBuilder>(
                  getDevice(),
                  getParentForChildren(),
                  isClean());
          device_ = null;
        }
        return deviceBuilder_;
      }

      private java.lang.Object countryCode_ = "";
      /**
       * <code>optional string countryCode = 31;</code>
       */
      public boolean hasCountryCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string countryCode = 31;</code>
       */
      public java.lang.String getCountryCode() {
        java.lang.Object ref = countryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            countryCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string countryCode = 31;</code>
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        java.lang.Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string countryCode = 31;</code>
       */
      public Builder setCountryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string countryCode = 31;</code>
       */
      public Builder clearCountryCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        countryCode_ = getDefaultInstance().getCountryCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string countryCode = 31;</code>
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        countryCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object languageCode_ = "";
      /**
       * <code>optional string languageCode = 32;</code>
       */
      public boolean hasLanguageCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string languageCode = 32;</code>
       */
      public java.lang.String getLanguageCode() {
        java.lang.Object ref = languageCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            languageCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string languageCode = 32;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageCodeBytes() {
        java.lang.Object ref = languageCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          languageCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string languageCode = 32;</code>
       */
      public Builder setLanguageCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        languageCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string languageCode = 32;</code>
       */
      public Builder clearLanguageCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        languageCode_ = getDefaultInstance().getLanguageCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string languageCode = 32;</code>
       */
      public Builder setLanguageCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        languageCode_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:barrage.PBDataRequest)
    }

    static {
      defaultInstance = new PBDataRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:barrage.PBDataRequest)
  }

  public interface PBDataResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:barrage.PBDataResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 resultCode = 1 [default = 0];</code>
     */
    boolean hasResultCode();
    /**
     * <code>required int32 resultCode = 1 [default = 0];</code>
     */
    int getResultCode();

    /**
     * <code>optional int32 requestId = 2;</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional int32 requestId = 2;</code>
     */
    int getRequestId();

    /**
     * <code>optional int32 version = 3;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 3;</code>
     */
    int getVersion();

    /**
     * <code>optional int32 totalCount = 4;</code>
     *
     * <pre>
     * 返回记录总数
     * </pre>
     */
    boolean hasTotalCount();
    /**
     * <code>optional int32 totalCount = 4;</code>
     *
     * <pre>
     * 返回记录总数
     * </pre>
     */
    int getTotalCount();
  }
  /**
   * Protobuf type {@code barrage.PBDataResponse}
   */
  public static final class PBDataResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:barrage.PBDataResponse)
      PBDataResponseOrBuilder {
    // Use PBDataResponse.newBuilder() to construct.
    private PBDataResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBDataResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBDataResponse defaultInstance;
    public static PBDataResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PBDataResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBDataResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              requestId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              totalCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orange.protocol.message.MessageProtos.PBDataResponse.class, com.orange.protocol.message.MessageProtos.PBDataResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<PBDataResponse> PARSER =
        new com.google.protobuf.AbstractParser<PBDataResponse>() {
      public PBDataResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBDataResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBDataResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>required int32 resultCode = 1 [default = 0];</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 resultCode = 1 [default = 0];</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    public static final int REQUESTID_FIELD_NUMBER = 2;
    private int requestId_;
    /**
     * <code>optional int32 requestId = 2;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 requestId = 2;</code>
     */
    public int getRequestId() {
      return requestId_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>optional int32 version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int TOTALCOUNT_FIELD_NUMBER = 4;
    private int totalCount_;
    /**
     * <code>optional int32 totalCount = 4;</code>
     *
     * <pre>
     * 返回记录总数
     * </pre>
     */
    public boolean hasTotalCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 totalCount = 4;</code>
     *
     * <pre>
     * 返回记录总数
     * </pre>
     */
    public int getTotalCount() {
      return totalCount_;
    }

    private void initFields() {
      resultCode_ = 0;
      requestId_ = 0;
      version_ = 0;
      totalCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, requestId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, totalCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, requestId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orange.protocol.message.MessageProtos.PBDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.protocol.message.MessageProtos.PBDataResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code barrage.PBDataResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:barrage.PBDataResponse)
        com.orange.protocol.message.MessageProtos.PBDataResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orange.protocol.message.MessageProtos.PBDataResponse.class, com.orange.protocol.message.MessageProtos.PBDataResponse.Builder.class);
      }

      // Construct using com.orange.protocol.message.MessageProtos.PBDataResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        totalCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.protocol.message.MessageProtos.internal_static_barrage_PBDataResponse_descriptor;
      }

      public com.orange.protocol.message.MessageProtos.PBDataResponse getDefaultInstanceForType() {
        return com.orange.protocol.message.MessageProtos.PBDataResponse.getDefaultInstance();
      }

      public com.orange.protocol.message.MessageProtos.PBDataResponse build() {
        com.orange.protocol.message.MessageProtos.PBDataResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orange.protocol.message.MessageProtos.PBDataResponse buildPartial() {
        com.orange.protocol.message.MessageProtos.PBDataResponse result = new com.orange.protocol.message.MessageProtos.PBDataResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.totalCount_ = totalCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.protocol.message.MessageProtos.PBDataResponse) {
          return mergeFrom((com.orange.protocol.message.MessageProtos.PBDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orange.protocol.message.MessageProtos.PBDataResponse other) {
        if (other == com.orange.protocol.message.MessageProtos.PBDataResponse.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTotalCount()) {
          setTotalCount(other.getTotalCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orange.protocol.message.MessageProtos.PBDataResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orange.protocol.message.MessageProtos.PBDataResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int resultCode_ ;
      /**
       * <code>required int32 resultCode = 1 [default = 0];</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 resultCode = 1 [default = 0];</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required int32 resultCode = 1 [default = 0];</code>
       */
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 resultCode = 1 [default = 0];</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = 0;
        onChanged();
        return this;
      }

      private int requestId_ ;
      /**
       * <code>optional int32 requestId = 2;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 requestId = 2;</code>
       */
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <code>optional int32 requestId = 2;</code>
       */
      public Builder setRequestId(int value) {
        bitField0_ |= 0x00000002;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 requestId = 2;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>optional int32 version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 3;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 3;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        onChanged();
        return this;
      }

      private int totalCount_ ;
      /**
       * <code>optional int32 totalCount = 4;</code>
       *
       * <pre>
       * 返回记录总数
       * </pre>
       */
      public boolean hasTotalCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 totalCount = 4;</code>
       *
       * <pre>
       * 返回记录总数
       * </pre>
       */
      public int getTotalCount() {
        return totalCount_;
      }
      /**
       * <code>optional int32 totalCount = 4;</code>
       *
       * <pre>
       * 返回记录总数
       * </pre>
       */
      public Builder setTotalCount(int value) {
        bitField0_ |= 0x00000008;
        totalCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalCount = 4;</code>
       *
       * <pre>
       * 返回记录总数
       * </pre>
       */
      public Builder clearTotalCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        totalCount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:barrage.PBDataResponse)
    }

    static {
      defaultInstance = new PBDataResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:barrage.PBDataResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_barrage_PBDataRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_barrage_PBDataRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_barrage_PBDataResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_barrage_PBDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\007barrage\032\017Constants.prot" +
      "o\032\014Common.proto\"\217\001\n\rPBDataRequest\022\014\n\004typ" +
      "e\030\001 \002(\005\022\021\n\trequestId\030\002 \001(\005\022\017\n\007version\030\003 " +
      "\001(\005\022!\n\006device\030\036 \001(\0132\021.barrage.PBDevice\022\023" +
      "\n\013countryCode\030\037 \001(\t\022\024\n\014languageCode\030  \001(" +
      "\t\"_\n\016PBDataResponse\022\025\n\nresultCode\030\001 \002(\005:" +
      "\0010\022\021\n\trequestId\030\002 \001(\005\022\017\n\007version\030\003 \001(\005\022\022" +
      "\n\ntotalCount\030\004 \001(\005B,\n\033com.orange.protoco" +
      "l.messageB\rMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.orange.protocol.message.ConstantsProtos.getDescriptor(),
          com.orange.protocol.message.CommonProtos.getDescriptor(),
        }, assigner);
    internal_static_barrage_PBDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_barrage_PBDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_barrage_PBDataRequest_descriptor,
        new java.lang.String[] { "Type", "RequestId", "Version", "Device", "CountryCode", "LanguageCode", });
    internal_static_barrage_PBDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_barrage_PBDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_barrage_PBDataResponse_descriptor,
        new java.lang.String[] { "ResultCode", "RequestId", "Version", "TotalCount", });
    com.orange.protocol.message.ConstantsProtos.getDescriptor();
    com.orange.protocol.message.CommonProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
